message("============================================================")
message("Description:")
message("CROP-seq analysis: check knockdown efficiency by targets remaining (UMI level)")
message("Compulsory Arguments:")
message("--workDir= full working directory where results will be generated")
message("--ExpFile= full path to pre-processed expression matrix")
message("--gRNAFile= full path to gRNA assignment file generated by gRNA assigning script")
message("--jobName= name of the CROP-seq run")
message("Optional Arguments:")
message("--Normalization= whether to use scran or tpm to normalize expression n scran as default ")
message("=============================================================")
message("\n")
#manual

args <- commandArgs(trailingOnly = T)
###########################################################################
### full working directory where results will be generated
workDir <- args[grep("--workDir=", args)] 
workDir <- substr(workDir, 11, nchar(workDir))
message("working directory:")
message(workDir)
###########################################################################
### full path to pre-processed expression matrix
ExpFile <- args[grep("--ExpFile=", args)] 
ExpFile <- substr(ExpFile, 11, nchar(ExpFile))
message("ExpFile:")
message(ExpFile)
###########################################################################
### full path to gRNA assignment file generated by gRNA assigning script
gRNAFile <- args[grep("--gRNAFile=", args)] 
gRNAFile <- substr(gRNAFile, 12, nchar(gRNAFile))
message("gRNAFile:")
message(gRNAFile)
###########################################################################
### name of the CROP-seq run
jobName <- args[grep("--jobName=", args)] 
jobName <- substr(jobName, 11, nchar(jobName))
message("job name:")
message(jobName)
##########################################################################
### whether to use scran or tpm to normalize expression
Normalization <- args[grep("--Normalization=", args)] 
Normalization <- substr(Normalization, 17, nchar(Normalization))
message("Normalization method:")
message(Normalization)
##########################################################################
### minimum number of cells coverage 
cellNo <- args[grep("--cellNo=", args)] 
cellNo <- as.numeric(substr(cellNo, 10, nchar(cellNo)))
message("Minimum No of cells:")
message(cellNo)
##########################################################################
### whether to select cells with strongest knockdown 
SelectCell <- args[grep("--SelectCell=", args)] 
SelectCell <- substr(SelectCell, 14, nchar(SelectCell))
message("SelectCell:")
message(SelectCell)
##########################################################################
### whether to use multiple gRNA cells 
Multi <- args[grep("--Multi=", args)] 
Multi <- substr(Multi, 9, nchar(Multi))
message("Multi:")
message(Multi)
##########################################################################
#arguments

target_remaining_selection <- function(mr,index,target_remaining) {
  print(paste0("Select gRNA for ",mr))
  if (is.null(target_remaining[[index[1]]])&is.null(target_remaining[[index[2]]])) return(NULL)
  else if (is.null(target_remaining[[index[1]]])&!is.null(target_remaining[[index[2]]])) 
    return(assign(names(target_remaining[index[2]]),target_remaining[[index[2]]]))
  else if (!is.null(target_remaining[[index[1]]])&is.null(target_remaining[[index[2]]])) 
    return(assign(names(target_remaining[index[1]]),target_remaining[[index[1]]]))
  else if (is.na(median(target_remaining[[index[1]]],na.rm = T))&is.na(median(target_remaining[[index[2]]],na.rm = T))) return(NULL)
  else if (is.na(median(target_remaining[[index[1]]],na.rm = T))&!is.na(median(target_remaining[[index[2]]],na.rm = T))) 
    return(assign(names(target_remaining[index[2]]),target_remaining[[index[2]]]))
  else if (!is.na(median(target_remaining[[index[1]]],na.rm = T))&is.na(median(target_remaining[[index[2]]],na.rm = T))) 
    return(assign(names(target_remaining[index[1]]),target_remaining[[index[1]]]))
  else if (median(target_remaining[[index[1]]],na.rm = T)<=median(target_remaining[[index[2]]],na.rm = T)) 
    return(assign(names(target_remaining[index[1]]),target_remaining[[index[1]]]))
  else 
    return(assign(names(target_remaining[index[2]]),target_remaining[[index[2]]]))
}
target_remaining_selection_index <- function(mr,index,target_remaining) {
  print(paste0("Select gRNA for ",mr))
  if (is.null(target_remaining[[index[1]]])&is.null(target_remaining[[index[2]]])) return(NULL)
  else if (is.null(target_remaining[[index[1]]])&!is.null(target_remaining[[index[2]]])) 
    return(index[2])
  else if (!is.null(target_remaining[[index[1]]])&is.null(target_remaining[[index[2]]])) 
    return(index[1])
  else if (is.na(median(target_remaining[[index[1]]],na.rm = T))&is.na(median(target_remaining[[index[2]]],na.rm = T))) return(NULL)
  else if (is.na(median(target_remaining[[index[1]]],na.rm = T))&!is.na(median(target_remaining[[index[2]]],na.rm = T))) 
    return(index[2])
  else if (!is.na(median(target_remaining[[index[1]]],na.rm = T))&is.na(median(target_remaining[[index[2]]],na.rm = T))) 
    return(index[1])
  else if (median(target_remaining[[index[1]]],na.rm = T)<=median(target_remaining[[index[2]]],na.rm = T)) 
    return(index[1])
  else 
    return(index[2])
}
  


set.seed(41)
library(org.Hs.eg.db,quietly = T,verbose = F)
library(ggplot2,quietly = T,verbose = F)

setwd(workDir)
### Load exprs from preliminary analysis.
load(ExpFile)
load(gRNAFile)

### Take cells with only 1 gRNA assigned. #######################################################
if(Multi) {
  exprs <- exprs[,sapply(gRNA_assigned,length)>0]
  gRNA_assigned <- gRNA_assigned[sapply(gRNA_assigned,length)>0]
} else {
  exprs <- exprs[,sapply(gRNA_assigned,length)==1]
  gRNA_assigned <- gRNA_assigned[sapply(gRNA_assigned,length)==1]
}





if (Normalization=="tpm") {
  exprs_norm <- apply(exprs,2,function(v){1e6*v/sum(v)})
} else {
  s <- scran::computeSumFactors(exprs,c(20,40,60,80,100))
  exprs_norm <- t(t(exprs)/s*mean(s))
}



gRNAs <- rownames(exprs_gRNA)
# Get cell ids of each MR group.
groups <- sapply(gRNAs, function(s){
  grep(paste0(g,""),gRNA_assigned)
})
negative_group <- grep("CONTROL",gRNA_assigned)
if(length(negative_group)<100) negative_group <- grep("",gRNA_assigned)


### For each gRNA, calculate the gRNA remaining. ################################################
### Calculation was done by comparing each gRNA group with the same number of NC cells. #########
### Bootstrap 100 times. ########################################################################
gRNA_detected <- unique(unlist(gRNA_assigned))
gRNA_detected <- gRNA_detected[grep("CONTROL",gRNA_detected,invert = T)]
MRs <- sapply(gRNA_detected,function(g){strsplit(g,split = '-')[[1]][1]})
gRNA_detected <- gRNA_detected[MRs%in%keys(org.Hs.eg.db,keytype="SYMBOL")]
gRNA_detected <- gRNA_detected[sapply(groups[gRNA_detected],length)>=cellNo]
MRs <- unique(sapply(gRNA_detected,function(g){strsplit(g,split = '-')[[1]][1]}))
  
target_remaining <- lapply(gRNA_detected, function(g){
  ### Get cell indexs. ###
  cells <- grep(paste0(g,""),gRNA_assigned)
  
  ### Get target index. ###
  MR <- strsplit(g,'-')[[1]][1]
  ensg <- select(org.Hs.eg.db,MR,columns = "ENSEMBL",keytype = "SYMBOL")$ENSEMBL
  ensg<- intersect(ensg,rownames(exprs_norm))
  if (SelectCell) cells <- sort(exprs_norm[ensg,cells],decreasing = F)[1:cellNo]
  if (length(ensg)>0) {
    ### Calculate. ####
    if (length(cells)==0) return(NULL)
    else {
      nc_distri <- sapply(1:100, function(i){
        return(sum(exprs_norm[ensg,sample(negative_group,length(cells),replace=T)]))
      })
      if (median(nc_distri)==0) {
        temp <- sum(exprs_norm[ensg,cells])/nc_distri
        #temp[is.na(temp)] <- 0
        temp[is.infinite(temp)] <- NaN
        return(temp)
        #return(NULL)
      }
      else {
        temp <- sum(exprs_norm[ensg,cells])/nc_distri
        #temp[is.na(temp)] <- 0
        temp[is.infinite(temp)] <- NaN
        return(temp)
      }
    }
  }
})
names(target_remaining) <- gRNA_detected
target_remaining_null <- lapply(gRNA_detected, function(g){
  ### Get cell indexs. ###
  cells <- grep(paste0(g,""),gRNA_assigned)
  cells <- sample(1:ncol(exprs_norm),length(cells),replace=T)
  ### Get target index. ###
  MR <- strsplit(g,'-')[[1]][1]
  ensg <- select(org.Hs.eg.db,MR,columns = "ENSEMBL",keytype = "SYMBOL")$ENSEMBL
  ensg<- intersect(ensg,rownames(exprs_norm))
  if (SelectCell) cells <- sort(exprs_norm[ensg,cells],decreasing = F)[1:cellNo]
  if (length(ensg)>0) {
    ### Calculate. ####
    if (length(cells)==0) return(NULL)
    else {
      nc_distri <- sapply(1:100, function(i){
        return(sum(exprs_norm[ensg,sample(negative_group,length(cells),replace=T)]))
      })
      if (median(nc_distri)==0) {
        temp <- sum(exprs_norm[ensg,cells])/nc_distri
        #temp[is.na(temp)] <- 0
        temp[is.infinite(temp)] <- NaN
        return(temp)
        #return(NULL)
      }
      else {
        temp <- sum(exprs_norm[ensg,cells])/nc_distri
        #temp[is.na(temp)] <- 0
        temp[is.infinite(temp)] <- NaN
        return(temp)
      }
    }
  }
})
names(target_remaining_null) <- gRNA_detected

target_remaining_high <- target_remaining[sapply(target_remaining, function(v){sum(is.na(v))/length(v)<=0.5})]
target_remaining_selected <- lapply(MRs, function(mr){
  index <- grep(paste0(mr,"-"),names(target_remaining_high))
  if (length(index)==1) return(assign(names(target_remaining_high[index[1]]),target_remaining_high[[index[1]]]))
  if (length(index)>1) {
    max_index <- index[1]
    for (i in 2:length(index)) {
      max <- target_remaining_selection(mr,c(max_index,index[i]),target_remaining_high)
      max_index <- target_remaining_selection_index(mr,c(max_index,index[i]),target_remaining_high)
    }
  }
  return(max)
})
target_remaining_selected <- target_remaining_selected[!sapply(target_remaining_selected,is.function)]
target_remaining_selected_index <- as.vector(lapply(MRs, function(mr){
  index <- grep(paste0(mr,"-"),names(target_remaining_high))
  if (length(index)==1) return(index)
  if (length(index)>1) {
    max <- index[1]
    for (i in 2:length(index)) {
      max <- target_remaining_selection_index(mr,c(max,index[i]),target_remaining_high)
    }
  }
  return(max)
}))
target_remaining_selected_index <- target_remaining_selected_index[!sapply(target_remaining_selected_index,is.function)]
### Plot boxplot by MR. ##########################################################################
color <- rep("black",times=length(target_remaining_selected))
color[sapply(target_remaining_selected, function(v){sum(is.na(v))/length(v)>0.5})] <- "red"
pdf_name <- paste0("Targets_Remaining_by_MRs_",cellNo,"cells")
if(Multi) pdf_name<-paste0(pdf_name,"_multi")
if(SelectCell) pdf_name<-paste0(pdf_name,"_select")
pdf(paste0(pdf_name,".pdf"),width = length(target_remaining_selected)/4,height = 7)
par(lwd=2)
Targets_Remaining_order<-order(sapply(target_remaining_selected, function(v){
  if (!is.null(v)) return(median(v,na.rm=T))
  else return(-Inf)
}))
Targets_Remaining_order <- Targets_Remaining_order[(1+sum(sapply(target_remaining_selected,is.null))):(length(Targets_Remaining_order))]
boxplot(target_remaining_selected[Targets_Remaining_order],border=color[Targets_Remaining_order],
        pch='.',ylim=c(0,1),horizontal=F,names=NA,ylab="Targets Remaining",outline = F)
abline(h=c(0.2,0.5,1),col=c("red","pink","black"),lty=1)
text(2:(length(Targets_Remaining_order)+1)-0.5,par("usr")[3]-0.03,cex = 0.8,
     labels=paste0(paste(MRs[Targets_Remaining_order],sapply(groups[gRNA_detected][as.numeric(target_remaining_selected_index[Targets_Remaining_order])],length),sep="(n="),")"),
     srt=45,pos=2,xpd=TRUE,col=color[Targets_Remaining_order])
dev.off()
rda_name <- paste0("Targets_Remaining_by_MRs_",cellNo,"cells")
if(Multi) rda_name<-paste0(rda_name,"_multi")
if(SelectCell) rda_name<-paste0(rda_name,"_select")
save(target_remaining_selected,Targets_Remaining_order,file = paste0(rda_name,".rda"))

### Plot boxplot by guides ##########################################################################
color <- rep("black",times=length(target_remaining))
color[sapply(target_remaining, function(v){sum(is.na(v))/length(v)>0.5})] <- "red"
pdf_name <- paste0("Targets_Remaining_by_guides_",cellNo,"cells")
if(Multi) pdf_name<-paste0(pdf_name,"_multi")
if(SelectCell) pdf_name<-paste0(pdf_name,"_select")
pdf(paste0(pdf_name,".pdf"),width = length(target_remaining)/4,height = 16)
par(lwd=2,mfrow=c(2,1))
Targets_Remaining_order<-order(sapply(target_remaining, function(v){
  if (is.null(v)) return(Inf)
  #if ((sum(is.na(v))/length(v))>0.5) return(Inf)
  else return(median(v,na.rm=T))
}))
Targets_Remaining_order <- Targets_Remaining_order[1:(length(Targets_Remaining_order)-sum(sapply(target_remaining,is.null)))]
boxplot(target_remaining[Targets_Remaining_order],border=color[Targets_Remaining_order],
        pch='.',ylim=c(0,1),horizontal=F,names=NA,ylab="Targets Remaining",outline = F)
abline(h=c(0.2,0.5,1),col=c("red","pink","black"),lty=1)
text(2:(length(Targets_Remaining_order)+1)-0.5,par("usr")[3]-0.023,cex=0.67,
     labels=paste0(paste(gRNA_detected[Targets_Remaining_order],sapply(groups[gRNA_detected[Targets_Remaining_order]],length),sep="(n="),")"),
     srt=45,pos=2,xpd=TRUE,col=color[Targets_Remaining_order])

color <- rep("black",times=length(target_remaining_null))
color[sapply(target_remaining_null, function(v){sum(is.na(v))/length(v)>0.5})] <- "red"
Targets_Remaining_order<-order(sapply(target_remaining_null, function(v){
  if (!is.null(v)) return(median(v,na.rm=T))
  else return(Inf)
}))
Targets_Remaining_order <- Targets_Remaining_order[1:(length(Targets_Remaining_order)-sum(sapply(target_remaining_null,is.null)))]
boxplot(target_remaining_null[Targets_Remaining_order],border=color[Targets_Remaining_order],
        pch='.',ylim=c(0,2),horizontal=F,names=NA,ylab="Targets Remaining",outline = F)
abline(h=c(0.2,0.5,1),col=c("red","pink","black"),lty=1)
text(2:(length(Targets_Remaining_order)+1)-0.5,par("usr")[3]-0.023,cex=0.67,
     labels=paste0(paste(gRNA_detected[Targets_Remaining_order],sapply(groups[gRNA_detected],length)[Targets_Remaining_order],sep="(n="),")"),
     srt=45,pos=2,xpd=TRUE,col=color[Targets_Remaining_order])
dev.off()
rda_name <- paste0("Targets_Remaining_by_guides_",cellNo,"cells")
if(Multi) rda_name<-paste0(rda_name,"_multi")
if(SelectCell) rda_name<-paste0(rda_name,"_select")
save(target_remaining,Targets_Remaining_order,file = paste0(rda_name,".rda"))


target_remaining_med <- sapply(target_remaining, function(v){
  if (!is.null(v)) return(median(v,na.rm=T))
  else return(NA)
})
target_remaining_null_med <- sapply(target_remaining_null, function(v){
  if (!is.null(v)) return(median(v,na.rm=T))
  else return(NA)
})
nonNA <- (!is.na(target_remaining_med))&(!is.na(target_remaining_null_med))
x <- data.frame(Value=c(target_remaining_med[nonNA],target_remaining_null_med[nonNA]),
                treat=c(rep("CRISPRi",times=length(target_remaining_med[nonNA])),rep("Null",times=length(target_remaining_null_med[nonNA]))))

pdf_name <- paste0("Targets_Remaining_by_guides_density_",cellNo,"cells")
if(Multi) pdf_name<-paste0(pdf_name,"_multi")
if(SelectCell) pdf_name<-paste0(pdf_name,"_select")
pdf(paste0(pdf_name,".pdf"),width = 7,height = 7)

# Use semi-transparent fill
p<-ggplot(x, aes(x=Value, fill=treat)) + geom_density(alpha=0.4)
p
dev.off()



