print("============================================================")
print("Description:")
print("CellRanger results pre-processing.")
print("Compulsory Arguments:")
print("--workDir=full working directory where results will be generated")
print("--matrixDir= full path to directory of filtered_feature_bc_matrix generated by CellRanger")
print("--jobName= name of the CellRanger run")
print("--minUMIcount= minimum UMI count per cell")
print("--maxUMIcount= maximum UMI count per cell")
print("=============================================================")
print("\n")
#manual

args <- commandArgs(trailingOnly = T)
workDir <- args[grep("--workDir=", args)] 
workDir <- substr(workDir, 11, nchar(workDir))# full working directory where results will be generated
print("Working directory:")
print(workDir)
matrixDir <- args[grep("--matrixDir=", args)] 
matrixDir <- substr(matrixDir, 13, nchar(matrixDir))# full path to directory of filtered_feature_bc_matrix generated by CellRanger
print("Filtered_feature_bc_matrix directory:")
print(matrixDir)
jobName <- args[grep("--jobName=", args)] 
jobName <- substr(jobName, 11, nchar(jobName))# name of the CROP-seq run
print("Job name:")
print(jobName)
minUMIcount <- args[grep("--minUMIcount=", args)] 
minUMIcount <- as.numeric(substr(minUMIcount, 15, nchar(minUMIcount)))# minimum UMI count per cell
print("Minimum UMI count per cell:")
print(minUMIcount)
maxUMIcount <- args[grep("--maxUMIcount=", args)] 
maxUMIcount <- as.numeric(substr(maxUMIcount, 15, nchar(maxUMIcount)))# maximum UMI count per cell
print("Maximum UMI count per cell:")
print(maxUMIcount)
#arguments



##############################################################################################
### Function: CleanUpCells
### Clean up non-viable cells (low total UMI) and multiplets (high total UMI).
### Check output plots to see if the lower and upper need to be adjusted.
### Args:
###       exprs_mat: raw UMI count matrix with rows as genes and columns as cells
###       lower: lower limit of UMI counts
###       upper: upper limit of UMI counts
CleanUpCells <- function(exprs_mat,lower=NULL,upper=NULL) {
  # Calculate UMI counts per cell
  UMI_counts <- apply(exprs_mat, 2, sum)
  # default lower=5000
  if (is.null(lower)) lower<-5000
  # default upper=upper 20% quantile (assuming 20% multiplet rate)
  if (is.null(upper)) upper<-quantile(UMI_counts,probs = 0.8)
  ##############################################################
  # plot UMI per cell before filter
  pdf("UMIPerCell_prefilter.pdf",width=7,height=7)
  plot(density(UMI_counts),lwd=2,xlab = "UMI per cell",font=2,cex.lab=1.5,main = "UMI per cell")
  abline(v=c(lower,upper),col="red")
  dev.off()
  # gene per cell before filter
  pdf("GenePerCell_prefilter.pdf",width=7,height=7)
  plot(density(apply(exprs_mat, 2, function(v){length(which(v>0))})),lwd=2,xlab = "Genes detected per cell",font=2,cex.lab=1.5,main = "Genes (UMI>0) detected per cell")
  dev.off()
  #############################################################
  # filter
  proper_UMI <- which((UMI_counts>=lower)&(UMI_counts<=upper))
  print(paste0("Number of non-viable cells: ",sum(UMI_counts<lower)))
  print(paste0("Number of mutiplets: ",sum(UMI_counts>upper)))
  exprs_mat <- exprs_mat[,proper_UMI]
  
  ############################################################
  # UMI per cell after filter
  pdf("UMIPerCell_postfilter.pdf",width=7,height=7)
  plot(density(apply(exprs_mat, 2, sum)),lwd=2,xlab = "UMI per cell",font=2,cex.lab=1.5,main = "UMI per cell after filtering")
  abline(v=c(lower,upper),col="red")
  dev.off()
  # Gene per cell after filter
  pdf("GenePerCell_postfilter.pdf",width=7,height=7)
  plot(density(apply(exprs_mat, 2, function(v){length(which(v>0))})),lwd=2,xlab = "Genes detected per cell",font=2,cex.lab=1.5,main = "Genes detected (UMI>0) per cell after filtering")
  dev.off()
  ############################################################
  
  return(exprs_mat)
}
##############################################################################################


setwd(workDir)

### Load matrix ##############################################################################
suppressPackageStartupMessageslibrary((Matrix))

barcode.path <- paste0(matrixDir, grep("barcode",list.files(matrixDir),value = T))
if (length(grep("genes",list.files(matrixDir)))==0) {
  features.path <- paste0(matrixDir, grep("features",list.files(matrixDir),value = T))
  } else {
    features.path <- paste0(matrixDir, grep("genes",list.files(matrixDir),value = T))
  }
matrix.path <- paste0(matrixDir, grep("matrix",list.files(matrixDir),value = T))
mat <- readMM(file = matrix.path)
feature.names = read.delim(features.path, 
                           header = FALSE,
                           stringsAsFactors = FALSE)
barcode.names = read.delim(barcode.path, 
                           header = FALSE,
                           stringsAsFactors = FALSE)
colnames(mat) = barcode.names$V1
rownames(mat) = feature.names$V1

exprs <- as.matrix(mat)
rm(mat,barcode.names,feature.names,matrix.path,matrixDir,barcode.path,features.path)
##############################################################################################

### Clean up cells.
exprs <- CleanUpCells(exprs,lower=minUMIcount,upper=maxUMIcount)

### Save into RDA.
save(exprs,file = paste0(jobName,".rda"))
